drop table users;

CREATE TABLE users (
  USER_ID NUMBER(10) NOT NULL,
  USERNAME VARCHAR22(45) NOT NULL,
  PASSWORD VARCHAR22(45) NOT NULL,
  ENABLED char(1) check (ENABLED in ('Y','N')) NOT NULL,
  PRIMARY KEY (USER_ID)
);

drop table user_roles;

CREATE TABLE user_roles (
  USER_ROLE_ID NUMBER(10)  NOT NULL,
  USER_ID NUMBER(10)  NOT NULL,
  AUTHORITY VARCHAR2(45) NOT NULL,
  PRIMARY KEY (USER_ROLE_ID),
  CONSTRAINT FK_user_roles FOREIGN KEY (USER_ID) REFERENCES users(USER_ID)
);